### ISSUE TITLE
Document additional requirements for building Intecture

### ISSUE THREAD

**Issue by rushmorem** [intecture/cli#8]
Unfortunately I don't have enough time to debug and put together a proper pull request right now so I will just note this here for now:-

In order to build the `cli` using `cargo build --release` on [NixOS](https://nixos.org/) I had to specify the following libraries as build inputs:-

```
gcc openssl zeromq czmq gnumake pkgconfig cmake zlib
```

When I try to build both the `agent` and `auth` servers, they fail with the following note at the end:-

```
= note: ~/projects/intecture/auth/target/release/deps/libczmq-e83fe7832016cf39.rlib(czmq-e83fe7832016cf39.czmq-zframe.o): In function `czmq::zframe::ZFrame::meta::h11bd2a4a56fcddc7':
          czmq-zframe.rs:(.text._ZN4czmq6zframe6ZFrame4meta17h11bd2a4a56fcddc7E+0x134): undefined reference to `zframe_meta'
          collect2: error: ld returned 1 exit status
```

@petehayes102 Any idea what I'm missing here?

**Comment by itpetey** [comment]
Thanks for the report! I haven't used/tested on NixOS so I'm not 100% what's going on here. Sounds like a linker issue? Are those libs in the default location (e.g. /usr/lib)? I'll see if I can debug this in the next few days, but I have zero experience with NixOS so it might take a while.

As for the other error, what version of CZMQ and ZMQ are you using? It might be related to this issue? https://github.com/zeromq/czmq/commit/19c762954b4a6b6e64d951410a5ba650dee0dd1a

**Comment by rushmorem** [comment]
> Thanks for the report!

It's the least I could do. I love Rust. This was one of the things on my wishlist. The fact that it's API driven is  awesome. This project is amazing! Thank you for it. You have no idea how delighted I was when I discovered it :)

> Sounds like a linker issue? Are those libs in the default location (e.g. /usr/lib)? I'll see if I can debug this in the next few days, but I have zero experience with NixOS so it might take a while.

Don't worry about that. There is nothing to debug. That's how NixOS works. It doesn't leak dependencies. They have to be specified explicitly. From one DevOps guy to another, you should totally try it. I have been using it for more than 4 years and I love it.

Edit: The main reason I opened this issue is to have all the dependencies clearly documented.

> As for the other error, what version of CZMQ and ZMQ are you using? It might be related to this issue? 

I think you are right. NixOS currently has [v3.0.2](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.czmq.x86_64-linux) in its packages so it's probably that issue. I will update it and rebuild.

Edit: I just noticed that the pull request you linked to was talking about the version of ZMQ and not CZMQ. I'm running NixOS 16.09 which has CZMQ v3.0.2 and ZMQ v4.1.4. I'm updating to latest versions of both libraries.

**Comment by rushmorem** [comment]
You were right. I have updated `zmq` to v4.2.2 and `czmq` to v4.0.2 and now all three build fine. I'm now creating [Nix](http://nixos.org/nix/) packages for them.

**Comment by itpetey** [comment]
>This project is amazing! Thank you for it.

Wow! That's high praise! Thanks for the encouragement mate. I hope Intecture lives up to the hype :)

>From one DevOps guy to another, you should totally try it. I have been using it for more than 4 years and I love it.

NixOS has been on my reading list for quite a while but I've had to defer it to work on this. Considering that NixOS and Intecture are in the same DevOps sphere, I should make an effort to support them.

Just a heads up that if you want to manage NixOS machines, I'd imagine there will need to be a patch to the API. Specifically a new target (`src/target/nixos.rs`) will need to be added to support all of NixOS's quirks, package manager etc. I recon I could get that done next week.

>Edit: The main reason I opened this issue is to have all the dependencies clearly documented.

You're right about the lack of docs. I'll make sure I put that into the `README.md` and website docs.

>You were right. I have updated zmq to v4.2.2 and czmq to v4.0.2 and now all three build fine. I'm now creating Nix packages for them.

Glad to hear that you're getting Intecture building properly. I should have documented the minimum lib versions. Duh! I'll add that to my todo list.

**Comment by rushmorem** [comment]
> Just a heads up that if you want to manage NixOS machines, I'd imagine there will need to be a patch to the API. Specifically a new target (src/target/nixos.rs) will need to be added to support all of NixOS's quirks, package manager etc. I recon I could get that done next week.

Yes I do want to manage NixOS machines. Thanks :)

Edit: I have a created a ticket to track progress on adding NixOS support. Your code is well laid out and easy to follow. I will put together a pull request within the next few days. I will let you know if I get stuck ;)

**Comment by rushmorem** [comment]
I just saw https://github.com/intecture/api/issues/14. Would you rather I wait till it lands?

**Comment by rushmorem** [comment]
I have finished packaging for Nix so once channels have updated say `nixos` (the default NixOS channel), users can install all packages as follows:-

```sh
nix-env -iA nixos.intecture-agent nixos.intecture-auth nixos.intecture-cli
```

**Comment by itpetey** [comment]
I didn't realise that you were packaging Intecture - I thought you meant ZeroMQ. Thanks!

I'm going to close this and create a new ticket with the documentation task. This thread got a bit crowded! 😛 I'm on Gitter if you want to discuss anything.
