### ISSUE TITLE
Make optional dependencies optional

### ISSUE THREAD

**Issue by rushmorem** [intecture/cli#9]
All the components should expose non-core components like `C` and `PHP` support as optional features which can be enabled or disabled. This can have a few benefits. For example, if this was the case I could have disabled `C` support when [czmq failed to build](https://github.com/intecture/cli/issues/8) for `auth` and `agent` servers since I only need Rust.

**Comment by itpetey** [comment]
Within the Rust code itself, the only link to PHP and C is the FFI code, which is actually dependency-free (and only present in the API, not the Auth or Agent components).

Intecture uses ZeroMQ to communicate with and authenticate its various components. Unfortunately we can't disable this to get around your other issue. I have been thinking about dropping support for CZMQ and bringing the extra functionality into Rust itself, which would eliminate one dependency. However that is a way off.

**Comment by itpetey** [comment]
Quick note on language bindings - the API has an FFI baked in, which lets C libs include it as a dependency in their code. I've written some C headers as well, which is the "C support" component. PHP has a standalone binding which is compiled separately from the API. The only way to enable PHP support is to specifically compile it and install the resulting libs yourself.

**Comment by rushmorem** [comment]
That totally makes sense. Thanks for explaining.
